name: validate-k8s-resource-integrity

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Validate k8s manifests YAML integrity 
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: manifests
          yamllint_config_filepath: yamllint/conf.yaml

      - name: Validate helm chart YAML integrity 
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: demo-chart/templates
          yamllint_config_filepath: yamllint/conf.yaml
      
      - name: Validate k8s manifests using conftest policies
        uses: instrumenta/conftest-action@master
        with:
          files: manifests
          policy: conftest

      - name: Validate helm charts using conftest policies
        uses: instrumenta/conftest-action/helm@master
        with:
          chart: demo-chart
          policy: conftest

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}